### ISSUE TITLE
Dailymotion

### ISSUE THREAD

**Issue by harryray33** [puddingspudding/persistent-video-volume#8]
Unfortunately Dailymotion doesn't save the volume level after a browser restart. It defaults back to full level. I've been caught out several times with it blasting at full volume.

I like the usefulness of this extension but unfortunately disabling the native volume control makes it a bit awkward.

**Comment by puddingspudding** [comment]
Thanks for the clarification. I'll look into it the next days

**Comment by harryray33** [comment]
Brilliant, thank you....

**Comment by puddingspudding** [comment]
Hi @harryray33 
I've uploaded a new version to the Chrome Webstore and Firefox Addons.
Changes:
Interval in which volume changes are applied were decreased.
Changes to the websites volume using its own volume control changes the addons volume.

**Comment by harryray33** [comment]
Thanks, the volume control is working but still a problem when the browser restarts..it's defaulting to 100% volume.

Also, don't know if possible but can the volume control be on a per page basis? For example, if I have the volume set at 6% and I change the volume to say 20% on the dailymotion page I'm watching is it possible to still have persistent volume left at 6% when start the next video?

**Comment by harryray33** [comment]
Im using 0.71 The problem is, I think, that the volume control on the site and the addons volume should be independent of each other.
ie. If I change the volume on the webpage it shouldn't also affect the overall add on volume.

**Comment by puddingspudding** [comment]
If the two volume controls would be independent of each other, in which scenario the addons volume changes the websites volume? At one point you want to change the websites volume based on the addon.
Right now, the addon frequently updates the websites volume, for all current video and audio elements, in order to affect every source of audio at any time. For sure there are more sophisticated ways to implement this.


Futher, I'm looking into adding volume control per website. See #6 for a little voting
Since there are multiple requests through github and firefox reviews, to have a per website based volume control, this is most likely the next thing to implement.

To your Dailymotion problem: Now I've observed your problem (100% volume), but only once every 10th times. No idea why :(

**Comment by harryray33** [comment]
I would like the addon volume to stay as I set it to stop the volume blaring out but at the same time I want to control the volume on the page I'm watching so that it doesn't affect videos on other pages.
A lot of the time there is a volume difference between different videos on the same site so if I have to increase the volume on one video I want the next video I open to go back to the addon volume.

I don't have a problem with you tube as I have the enhancer for youtube addon which consistently sets the volume at the level I've entered.

With me I get 100% volume with every restart without fail.
